---
title: "MDE I - GBIF"
author: "Horacio Samaniego <br/><smaller>horacio@ecoinformatica.cl</smaller>"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# load libraries
list.of.packages <- c("landscapemetrics","sf","mapview","terra","dplyr","RColorBrewer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages,dep=TRUE,repos = "http://cran.us.r-project.org")
```

## Modelos de Distribución de Especies

Descansan en la idea de que los organismos vivos establecemos una relación con el medio ambiente definido por sus variables bióticas y abióticas.

- El Nicho es el concepto que operativiza esta relación con las variables ambientales 

La construcción de MDE usan el concepto de nicho para:

 1.  Definir las relacion con variables ambientales
 2.  Predecir la distribución geográfica

## Etapas del ejecicio de MDE I{.smaller}

1. Sitios de ocurrencia (lon,lat)<br/>
  Usaremos  datos de GBIF [www.gbif.org](http://www.gbif.org) para obtener registros de ocurrencia del loro tricahue
2. Construiremos un set de datos geográficos para manipulación en R<br/>
  Como sólo tenemos datos donde ocurre, tenemos que generar datos de ausencias tambien. Las llamaremos: *pseudo-ausencias*, pues en realidad no sabemos si alli no hay.
3. Visualizar ourrencias de presencias (y de ausencias)<br/>
  Usaremos: `plot`, `ggplot` y `mapview` como herramientas de visualización estática e interactiva
4. Descarga de variables ambientales<br/>
  Descargaremos variables bioclimáticas desde [worldclim](http://www.worldclim.org). Les queda a Uds. descargar precipitaciones, temperaturas y radiación. Pueden buscar otras variables tambien, como uso del suelo usado en clases anteriores.
5. Selección de variables ambientales y evaluación de colinearidad<br/>
  Esto es necesario para generar un modelo que sea el mas parsimonioso posible y no "infle" los datos. Para eso, usaremos matrices de correlación. 

## Etapas del ejecicio de MDE II{.smaller}

6. Modelos de Distribución
  - librería `dismo`
  - GLM
  - Random Forest
  - Maxent (?)<br/>
  
  
